# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ea3f86e91ca68d55f611ea9e8be589b5fcaefcee687bdeb53504d2330866b8ef1d0b1029d892307d39fb442ebbe28cf566a1f1df61b0aa2f95bf9a460f0024

test:
  secret_key_base: 23d04541a0395761b2b37748e1dd3a15c60fde8f2087dab9dfd7cb1c6d9a45eb575e0dbe670b1d29539c81e4ac72548523d1158a7fc0e8963e0c68c9d236d7a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
